"""empty message

Revision ID: 66c0d4286476
Revises: 
Create Date: 2021-08-23 04:20:05.808763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c0d4286476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('criador', sa.String(), nullable=True),
    sa.Column('is_bet', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entradas')
    # ### end Alembic commands ###
