"""empty message

Revision ID: 900aa26f1828
Revises: 66c0d4286476
Create Date: 2021-08-23 04:22:46.444668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900aa26f1828'
down_revision = '66c0d4286476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas', sa.Column('criado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entradas', 'criado_em')
    # ### end Alembic commands ###
